-- SQL Schema para la base de datos de Supabase
-- Copia y pega este script en el SQL Editor de tu proyecto en Supabase (https://supabase.com)

-- 1. Crear la tabla de preguntas de estudio
create table if not exists public.study_questions (
    id bigint generated by default as identity primary key,
    level text not null,          -- 'semisenior', 'senior', 'principal'
    category text not null,       -- e.g. 'System Architecture'
    question text not null,
    answer text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS)
alter table public.study_questions enable row level security;

-- Eliminar políticas previas si existen
drop policy if exists "Allow public read access for study_questions" on public.study_questions;

-- Crear política que permite a cualquiera leer las preguntas
create policy "Allow public read access for study_questions"
    on public.study_questions for select
    to anon
    using (true);


-- 2. Crear la tabla de preguntas de cuestionario (quiz)
create table if not exists public.quiz_questions (
    id bigint generated by default as identity primary key,
    level text not null,          -- 'semisenior', 'senior', 'principal'
    question text not null,
    options jsonb not null,       -- Array JSON de opciones
    correct_index integer not null,
    explanation text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS)
alter table public.quiz_questions enable row level security;

-- Eliminar políticas previas si existen
drop policy if exists "Allow public read access for quiz_questions" on public.quiz_questions;

-- Crear política que permite a cualquiera realizar el cuestionario
create policy "Allow public read access for quiz_questions"
    on public.quiz_questions for select
    to anon
    using (true);
